CREATE TABLE EX2_9(
NUM1    NUMBER 
    CONSTRAINTS CHECK1 PRIMARY KEY, CHECK (NUM1 BETWEEN 1 AND 9),
GENDER  VARCHAR2(10) 
    CONSTRAINTS CHECK2 CHECK (GENDER IN ('MALE','FEMALE'))
);

ALTER TABLE EX2_9 DROP CONSTRAINTS CHECK1; 
ALTER TABLE EX2_9 DROP CONSTRAINTS CHECK2; 
ALTER TABLE EX2_9 DROP CONSTRAINTS SYS_C007032; 

DROP TABLE EX2_9;

SELECT CONSTRAINT_
